var annotated_dup =
[
    [ "Scene", "glossary.html#autotoc_md22", null ],
    [ "Rendering", "glossary.html#autotoc_md23", null ],
    [ "Pipeline", "glossary.html#autotoc_md24", null ],
    [ "Graphics / Rendering Pipeline", "glossary.html#autotoc_md25", null ],
    [ "Pixel", "glossary.html#autotoc_md26", null ],
    [ "Vertex", "glossary.html#autotoc_md27", null ],
    [ "Primitive / Face", "glossary.html#autotoc_md28", null ],
    [ "Mesh", "glossary.html#autotoc_md29", null ],
    [ "Vertex Shader", "glossary.html#autotoc_md30", null ],
    [ "Pixel / Fragment Shader", "glossary.html#autotoc_md31", null ],
    [ "Vertex Pipeline / Processor", "glossary.html#autotoc_md32", null ],
    [ "Vertex Processing / Shader Unit", "glossary.html#autotoc_md33", null ],
    [ "Pixel / Fragment Processor / Pipeline", "glossary.html#autotoc_md34", null ],
    [ "Fragment Processing / Shader Unit", "glossary.html#autotoc_md35", null ],
    [ "Unified Shader", "glossary.html#autotoc_md36", null ],
    [ "Fragment", "glossary.html#autotoc_md37", null ],
    [ "Raster Pipeline / ROP / Z-pipe", "glossary.html#autotoc_md38", null ],
    [ "Raster Operation Unit", "glossary.html#autotoc_md39", null ],
    [ "Fragment Crossbar", "glossary.html#autotoc_md40", null ],
    [ "Texel", "glossary.html#autotoc_md41", null ],
    [ "Texture", "glossary.html#autotoc_md42", null ],
    [ "Texture Unit", "glossary.html#autotoc_md43", null ],
    [ "Texture Filtering", "glossary.html#autotoc_md44", null ],
    [ "Isotropic Filtering", "glossary.html#autotoc_md45", null ],
    [ "Anisotropic Filtering", "glossary.html#autotoc_md46", null ],
    [ "MIP mapping", "glossary.html#autotoc_md47", null ],
    [ "Multitexturing", "glossary.html#autotoc_md48", null ],
    [ "Aliasing", "glossary.html#autotoc_md49", null ],
    [ "Antialiasing, AA", "glossary.html#autotoc_md50", null ],
    [ "Multisample Antialiasing, MSAA", "glossary.html#autotoc_md51", [
      [ "Quincunx Antialiasing (nVidia)", "glossary.html#autotoc_md52", null ],
      [ "AccuView Antialiasing (nVidia)", "glossary.html#autotoc_md53", null ],
      [ "Transparency Antialiasing (nVidia)", "glossary.html#autotoc_md54", null ],
      [ "Coverage Sampling Antialiasing, CSAA (nVidia)", "glossary.html#autotoc_md55", null ]
    ] ],
    [ "Supersampled Antialiasing, SSAA", "glossary.html#autotoc_md56", null ],
    [ "Shading", "glossary.html#autotoc_md57", [
      [ "Flat Shading", "glossary.html#autotoc_md58", null ],
      [ "Gouraud Shading", "glossary.html#autotoc_md59", null ],
      [ "Phong Shading", "glossary.html#autotoc_md60", null ],
      [ "Dot-product texture blending, DOT3", "glossary.html#autotoc_md61", null ]
    ] ],
    [ "Rendering Pipeline Architecture", "glossary.html#autotoc_md62", null ],
    [ "HW T&L - Hardware Transformation and Lighting", "glossary.html#autotoc_md63", [
      [ "Pre-Transform (pre-T&L) Cache", "glossary.html#autotoc_md64", null ],
      [ "Post-Transform (post-T&L) Cache", "glossary.html#autotoc_md65", null ]
    ] ],
    [ "Culling", "glossary.html#autotoc_md66", null ],
    [ "Hidden Surface Removal", "glossary.html#autotoc_md67", null ],
    [ "Depth Sorting", "glossary.html#autotoc_md68", null ],
    [ "AGP Fast Writes", "glossary.html#autotoc_md69", null ],
    [ "HyperZ (ATi)", "glossary.html#autotoc_md70", [
      [ "Hierarchical Z, HiZ", "glossary.html#autotoc_md71", null ],
      [ "Z Compression", "glossary.html#autotoc_md72", null ],
      [ "Fast Z Clear", "glossary.html#autotoc_md73", null ]
    ] ],
    [ "Lightspeed Memory Architecture, LMA (nVidia)", "glossary.html#autotoc_md74", null ],
    [ "Nvidia Shading Rasterizer, NSR (nVidia)", "glossary.html#autotoc_md75", null ],
    [ "Render to Vertex Buffer, R2VB", "glossary.html#autotoc_md76", null ],
    [ "High Dynamic Range Rendering, HDR", "glossary.html#autotoc_md77", null ],
    [ "Shadow Buffers (nVidia)", "glossary.html#autotoc_md78", null ],
    [ "UltraShadow (nVidia)", "glossary.html#autotoc_md79", null ],
    [ "UltraShadow II (nVidia)", "glossary.html#autotoc_md80", null ],
    [ "CompareByZdistance", "struct_compare_by_zdistance.html", "struct_compare_by_zdistance" ],
    [ "DDPIXELFORMAT", "struct_d_d_p_i_x_e_l_f_o_r_m_a_t.html", "struct_d_d_p_i_x_e_l_f_o_r_m_a_t" ],
    [ "DDSCAPS2", "struct_d_d_s_c_a_p_s2.html", "struct_d_d_s_c_a_p_s2" ],
    [ "DDSURFACEDESC2", "struct_d_d_s_u_r_f_a_c_e_d_e_s_c2.html", "struct_d_d_s_u_r_f_a_c_e_d_e_s_c2" ],
    [ "PR00FsReducedRenderingEngine", "class_p_r00_fs_reduced_rendering_engine.html", "class_p_r00_fs_reduced_rendering_engine" ],
    [ "PR00FsReducedRenderingEngineImpl", "class_p_r00_fs_reduced_rendering_engine_impl.html", "class_p_r00_fs_reduced_rendering_engine_impl" ],
    [ "PRREAxisAlignedBoundingBox", "class_p_r_r_e_axis_aligned_bounding_box.html", "class_p_r_r_e_axis_aligned_bounding_box" ],
    [ "PRREBoundingVolumeHierarchy", "class_p_r_r_e_bounding_volume_hierarchy.html", "class_p_r_r_e_bounding_volume_hierarchy" ],
    [ "PRRECamera", "class_p_r_r_e_camera.html", "class_p_r_r_e_camera" ],
    [ "PRREColor", "class_p_r_r_e_color.html", "class_p_r_r_e_color" ],
    [ "PRREFiledManaged", "class_p_r_r_e_filed_managed.html", "class_p_r_r_e_filed_managed" ],
    [ "PRREFiledManager", "class_p_r_r_e_filed_manager.html", "class_p_r_r_e_filed_manager" ],
    [ "PRREGLsnippets", "class_p_r_r_e_g_lsnippets.html", null ],
    [ "PRREhwAudio", "class_p_r_r_ehw_audio.html", "class_p_r_r_ehw_audio" ],
    [ "PRREhwAudioImpl", "class_p_r_r_ehw_audio_impl.html", "class_p_r_r_ehw_audio_impl" ],
    [ "PRREhwBase", "class_p_r_r_ehw_base.html", "class_p_r_r_ehw_base" ],
    [ "PRREhwCentralProcessor", "class_p_r_r_ehw_central_processor.html", "class_p_r_r_ehw_central_processor" ],
    [ "PRREhwCentralProcessorImpl", "class_p_r_r_ehw_central_processor_impl.html", "class_p_r_r_ehw_central_processor_impl" ],
    [ "PRREhwInfo", "class_p_r_r_ehw_info.html", "class_p_r_r_ehw_info" ],
    [ "PRREhwInfoImpl", "class_p_r_r_ehw_info_impl.html", "class_p_r_r_ehw_info_impl" ],
    [ "PRREhwSystemMemory", "class_p_r_r_ehw_system_memory.html", "class_p_r_r_ehw_system_memory" ],
    [ "PRREhwSystemMemoryImpl", "class_p_r_r_ehw_system_memory_impl.html", "class_p_r_r_ehw_system_memory_impl" ],
    [ "PRREhwVideo", "class_p_r_r_ehw_video.html", "class_p_r_r_ehw_video" ],
    [ "PRREhwVideoDiscoverOpenGL_1_1", "class_p_r_r_ehw_video_discover_open_g_l__1__1.html", "class_p_r_r_ehw_video_discover_open_g_l__1__1" ],
    [ "PRREhwVideoDiscoverOpenGL_1_2", "class_p_r_r_ehw_video_discover_open_g_l__1__2.html", "class_p_r_r_ehw_video_discover_open_g_l__1__2" ],
    [ "PRREhwVideoDiscoverOpenGL_1_3", "class_p_r_r_ehw_video_discover_open_g_l__1__3.html", "class_p_r_r_ehw_video_discover_open_g_l__1__3" ],
    [ "PRREhwVideoDiscoverOpenGL_1_4", "class_p_r_r_ehw_video_discover_open_g_l__1__4.html", "class_p_r_r_ehw_video_discover_open_g_l__1__4" ],
    [ "PRREhwVideoDiscoverOpenGL_1_5", "class_p_r_r_ehw_video_discover_open_g_l__1__5.html", "class_p_r_r_ehw_video_discover_open_g_l__1__5" ],
    [ "PRREhwVideoDiscoverOpenGL_2_0", "class_p_r_r_ehw_video_discover_open_g_l__2__0.html", "class_p_r_r_ehw_video_discover_open_g_l__2__0" ],
    [ "PRREhwVideoDiscoverOpenGL_2_1", "class_p_r_r_ehw_video_discover_open_g_l__2__1.html", "class_p_r_r_ehw_video_discover_open_g_l__2__1" ],
    [ "PRREhwVideoDiscoverOpenGL_3_0", "class_p_r_r_ehw_video_discover_open_g_l__3__0.html", "class_p_r_r_ehw_video_discover_open_g_l__3__0" ],
    [ "PRREhwVideoDiscoverOpenGL_3_1", "class_p_r_r_ehw_video_discover_open_g_l__3__1.html", "class_p_r_r_ehw_video_discover_open_g_l__3__1" ],
    [ "PRREhwVideoDiscoverOpenGL_3_2", "class_p_r_r_ehw_video_discover_open_g_l__3__2.html", "class_p_r_r_ehw_video_discover_open_g_l__3__2" ],
    [ "PRREhwVideoDiscoverOpenGL_3_3", "class_p_r_r_ehw_video_discover_open_g_l__3__3.html", "class_p_r_r_ehw_video_discover_open_g_l__3__3" ],
    [ "PRREhwVideoDiscoverOpenGL_4_0", "class_p_r_r_ehw_video_discover_open_g_l__4__0.html", "class_p_r_r_ehw_video_discover_open_g_l__4__0" ],
    [ "PRREhwVideoDiscoverOpenGL_4_1", "class_p_r_r_ehw_video_discover_open_g_l__4__1.html", "class_p_r_r_ehw_video_discover_open_g_l__4__1" ],
    [ "PRREhwVideoDiscoverOpenGL_4_2", "class_p_r_r_ehw_video_discover_open_g_l__4__2.html", "class_p_r_r_ehw_video_discover_open_g_l__4__2" ],
    [ "PRREhwVideoDiscoverOpenGL_4_3", "class_p_r_r_ehw_video_discover_open_g_l__4__3.html", "class_p_r_r_ehw_video_discover_open_g_l__4__3" ],
    [ "PRREhwVideoDiscoverOpenGLbase", "class_p_r_r_ehw_video_discover_open_g_lbase.html", "class_p_r_r_ehw_video_discover_open_g_lbase" ],
    [ "PRREhwVideoImpl", "class_p_r_r_ehw_video_impl.html", "class_p_r_r_ehw_video_impl" ],
    [ "PRREIIncrementalRenderPipeline", "class_p_r_r_e_i_incremental_render_pipeline.html", "class_p_r_r_e_i_incremental_render_pipeline" ],
    [ "PRREImage", "class_p_r_r_e_image.html", "class_p_r_r_e_image" ],
    [ "PRREImageManager", "class_p_r_r_e_image_manager.html", "class_p_r_r_e_image_manager" ],
    [ "PRREIRenderable", "class_p_r_r_e_i_renderable.html", "class_p_r_r_e_i_renderable" ],
    [ "PRREIRenderer", "class_p_r_r_e_i_renderer.html", "class_p_r_r_e_i_renderer" ],
    [ "PRREManaged", "class_p_r_r_e_managed.html", "class_p_r_r_e_managed" ],
    [ "PRREManager", "class_p_r_r_e_manager.html", "class_p_r_r_e_manager" ],
    [ "PRREMaterial", "class_p_r_r_e_material.html", "class_p_r_r_e_material" ],
    [ "PRREMaterialManager", "class_p_r_r_e_material_manager.html", "class_p_r_r_e_material_manager" ],
    [ "PRREMatrix", "class_p_r_r_e_matrix.html", "class_p_r_r_e_matrix" ],
    [ "PRREMesh3D", "class_p_r_r_e_mesh3_d.html", "class_p_r_r_e_mesh3_d" ],
    [ "PRREMesh3DManager", "class_p_r_r_e_mesh3_d_manager.html", "class_p_r_r_e_mesh3_d_manager" ],
    [ "PRREObject3D", "class_p_r_r_e_object3_d.html", "class_p_r_r_e_object3_d" ],
    [ "PRREObject3DManager", "class_p_r_r_e_object3_d_manager.html", "class_p_r_r_e_object3_d_manager" ],
    [ "PRREOctree", "class_p_r_r_e_octree.html", "class_p_r_r_e_octree" ],
    [ "PRREPosUpTarget", "class_p_r_r_e_pos_up_target.html", "class_p_r_r_e_pos_up_target" ],
    [ "PRRERendererHWfixedPipe", "class_p_r_r_e_renderer_h_wfixed_pipe.html", "class_p_r_r_e_renderer_h_wfixed_pipe" ],
    [ "PRRERendererHWfixedPipeImpl", "class_p_r_r_e_renderer_h_wfixed_pipe_impl.html", "class_p_r_r_e_renderer_h_wfixed_pipe_impl" ],
    [ "PRRERendererSWincremental", "class_p_r_r_e_renderer_s_wincremental.html", "class_p_r_r_e_renderer_s_wincremental" ],
    [ "PRRERendererSWincrementalImpl", "class_p_r_r_e_renderer_s_wincremental_impl.html", "class_p_r_r_e_renderer_s_wincremental_impl" ],
    [ "PRREScreen", "class_p_r_r_e_screen.html", "class_p_r_r_e_screen" ],
    [ "PRREScreenImpl", "class_p_r_r_e_screen_impl.html", "class_p_r_r_e_screen_impl" ],
    [ "PRRESharedSettings", "class_p_r_r_e_shared_settings.html", "class_p_r_r_e_shared_settings" ],
    [ "PRRETexture", "class_p_r_r_e_texture.html", "class_p_r_r_e_texture" ],
    [ "PRRETextureManager", "class_p_r_r_e_texture_manager.html", "class_p_r_r_e_texture_manager" ],
    [ "PRRETransformMatrix", "class_p_r_r_e_transform_matrix.html", "class_p_r_r_e_transform_matrix" ],
    [ "PRREuiFontWin", "class_p_r_r_eui_font_win.html", "class_p_r_r_eui_font_win" ],
    [ "PRREuiManager", "class_p_r_r_eui_manager.html", "class_p_r_r_eui_manager" ],
    [ "PRREuiManagerImpl", "class_p_r_r_eui_manager_impl.html", "class_p_r_r_eui_manager_impl" ],
    [ "PRREuiText", "class_p_r_r_eui_text.html", "class_p_r_r_eui_text" ],
    [ "PRREVector", "class_p_r_r_e_vector.html", "class_p_r_r_e_vector" ],
    [ "PRREVertexTransfer", "class_p_r_r_e_vertex_transfer.html", "class_p_r_r_e_vertex_transfer" ],
    [ "PRREWindow", "class_p_r_r_e_window.html", "class_p_r_r_e_window" ],
    [ "PRREWindowImpl", "class_p_r_r_e_window_impl.html", "class_p_r_r_e_window_impl" ],
    [ "PUREScissor", "class_p_u_r_e_scissor.html", "class_p_u_r_e_scissor" ],
    [ "TPRRE_MATERIAL_LAYER", "struct_t_p_r_r_e___m_a_t_e_r_i_a_l___l_a_y_e_r.html", "struct_t_p_r_r_e___m_a_t_e_r_i_a_l___l_a_y_e_r" ],
    [ "TPRRE_RECT_FLOAT", "struct_t_p_r_r_e___r_e_c_t___f_l_o_a_t.html", "struct_t_p_r_r_e___r_e_c_t___f_l_o_a_t" ],
    [ "TPRRE_RGB_FLOAT", "struct_t_p_r_r_e___r_g_b___f_l_o_a_t.html", "struct_t_p_r_r_e___r_g_b___f_l_o_a_t" ],
    [ "TPRRE_RGB_UBYTE", "struct_t_p_r_r_e___r_g_b___u_b_y_t_e.html", "struct_t_p_r_r_e___r_g_b___u_b_y_t_e" ],
    [ "TPRRE_RGBA_FLOAT", "struct_t_p_r_r_e___r_g_b_a___f_l_o_a_t.html", "struct_t_p_r_r_e___r_g_b_a___f_l_o_a_t" ],
    [ "TPRRE_RGBA_UBYTE", "struct_t_p_r_r_e___r_g_b_a___u_b_y_t_e.html", "struct_t_p_r_r_e___r_g_b_a___u_b_y_t_e" ],
    [ "TPRRE_SIZE_XY", "struct_t_p_r_r_e___s_i_z_e___x_y.html", "struct_t_p_r_r_e___s_i_z_e___x_y" ],
    [ "TPRRE_TRANSFORMED_VERTEX", "struct_t_p_r_r_e___t_r_a_n_s_f_o_r_m_e_d___v_e_r_t_e_x.html", "struct_t_p_r_r_e___t_r_a_n_s_f_o_r_m_e_d___v_e_r_t_e_x" ],
    [ "TPRRE_UVW", "struct_t_p_r_r_e___u_v_w.html", "struct_t_p_r_r_e___u_v_w" ],
    [ "TPRRE_XY", "struct_t_p_r_r_e___x_y.html", "struct_t_p_r_r_e___x_y" ],
    [ "TPRRE_XYZ", "struct_t_p_r_r_e___x_y_z.html", "struct_t_p_r_r_e___x_y_z" ],
    [ "TPRRE_XYZW", "struct_t_p_r_r_e___x_y_z_w.html", "struct_t_p_r_r_e___x_y_z_w" ]
];