var annotated_dup =
[
    [ "pge_network", "namespacepge__network.html", [
      [ "MsgApp", "structpge__network_1_1_msg_app.html", "structpge__network_1_1_msg_app" ],
      [ "MsgAppArea", "structpge__network_1_1_msg_app_area.html", "structpge__network_1_1_msg_app_area" ],
      [ "MsgClientAppVersionFromClient", "structpge__network_1_1_msg_client_app_version_from_client.html", "structpge__network_1_1_msg_client_app_version_from_client" ],
      [ "MsgUserConnectedServerSelf", "structpge__network_1_1_msg_user_connected_server_self.html", "structpge__network_1_1_msg_user_connected_server_self" ],
      [ "MsgUserDisconnectedFromServer", "structpge__network_1_1_msg_user_disconnected_from_server.html", null ],
      [ "PgeClient", "classpge__network_1_1_pge_client.html", "classpge__network_1_1_pge_client" ],
      [ "PgeClientStub", "classpge__network_1_1_pge_client_stub.html", "classpge__network_1_1_pge_client_stub" ],
      [ "PgeIClient", "classpge__network_1_1_pge_i_client.html", "classpge__network_1_1_pge_i_client" ],
      [ "PgeINetwork", "classpge__network_1_1_pge_i_network.html", "classpge__network_1_1_pge_i_network" ],
      [ "PgeIServer", "classpge__network_1_1_pge_i_server.html", "classpge__network_1_1_pge_i_server" ],
      [ "PgeIServerClient", "classpge__network_1_1_pge_i_server_client.html", "classpge__network_1_1_pge_i_server_client" ],
      [ "PgeNetwork", "classpge__network_1_1_pge_network.html", "classpge__network_1_1_pge_network" ],
      [ "PgeNetworkStub", "classpge__network_1_1_pge_network_stub.html", "classpge__network_1_1_pge_network_stub" ],
      [ "PgePacket", "structpge__network_1_1_pge_packet.html", "structpge__network_1_1_pge_packet" ],
      [ "PgeServer", "classpge__network_1_1_pge_server.html", "classpge__network_1_1_pge_server" ],
      [ "PgeServerStub", "classpge__network_1_1_pge_server_stub.html", "classpge__network_1_1_pge_server_stub" ]
    ] ],
    [ "Bullet", "class_bullet.html", "class_bullet" ],
    [ "PGEcfgFile", "class_p_g_ecfg_file.html", "class_p_g_ecfg_file" ],
    [ "PGEcfgProfiles", "class_p_g_ecfg_profiles.html", "class_p_g_ecfg_profiles" ],
    [ "PGEcfgVariable", "class_p_g_ecfg_variable.html", "class_p_g_ecfg_variable" ],
    [ "PgeClientImpl", "class_pge_client_impl.html", "class_pge_client_impl" ],
    [ "PgeGnsClient", "class_pge_gns_client.html", "class_pge_gns_client" ],
    [ "PgeGnsServer", "class_pge_gns_server.html", "class_pge_gns_server" ],
    [ "PgeGnsWrapper", "class_pge_gns_wrapper.html", "class_pge_gns_wrapper" ],
    [ "PgeNetworkImpl", "class_pge_network_impl.html", "class_pge_network_impl" ],
    [ "PgeOldNewValue", "class_pge_old_new_value.html", "class_pge_old_new_value" ],
    [ "PgeServerImpl", "class_pge_server_impl.html", "class_pge_server_impl" ],
    [ "PooledBullet", "class_pooled_bullet.html", "class_pooled_bullet" ],
    [ "Weapon", "class_weapon.html", "class_weapon" ],
    [ "WeaponManager", "class_weapon_manager.html", "class_weapon_manager" ]
];