var annotated_dup =
[
    [ "proofps_dd", "namespaceproofps__dd.html", [
      [ "CameraHandling", "classproofps__dd_1_1_camera_handling.html", "classproofps__dd_1_1_camera_handling" ],
      [ "Config", "classproofps__dd_1_1_config.html", "classproofps__dd_1_1_config" ],
      [ "DeathKillEventLister", "classproofps__dd_1_1_death_kill_event_lister.html", "classproofps__dd_1_1_death_kill_event_lister" ],
      [ "DeathMatchMode", "classproofps__dd_1_1_death_match_mode.html", "classproofps__dd_1_1_death_match_mode" ],
      [ "DrawableEventLister", "classproofps__dd_1_1_drawable_event_lister.html", "classproofps__dd_1_1_drawable_event_lister" ],
      [ "Durations", "structproofps__dd_1_1_durations.html", "structproofps__dd_1_1_durations" ],
      [ "EventLister", "classproofps__dd_1_1_event_lister.html", "classproofps__dd_1_1_event_lister" ],
      [ "Explosion", "classproofps__dd_1_1_explosion.html", "classproofps__dd_1_1_explosion" ],
      [ "FragTableRow", "structproofps__dd_1_1_frag_table_row.html", "structproofps__dd_1_1_frag_table_row" ],
      [ "GameMode", "classproofps__dd_1_1_game_mode.html", "classproofps__dd_1_1_game_mode" ],
      [ "GUI", "classproofps__dd_1_1_g_u_i.html", "classproofps__dd_1_1_g_u_i" ],
      [ "InputHandling", "classproofps__dd_1_1_input_handling.html", "classproofps__dd_1_1_input_handling" ],
      [ "Mapcycle", "classproofps__dd_1_1_mapcycle.html", "classproofps__dd_1_1_mapcycle" ],
      [ "MapItem", "classproofps__dd_1_1_map_item.html", "classproofps__dd_1_1_map_item" ],
      [ "Maps", "classproofps__dd_1_1_maps.html", "classproofps__dd_1_1_maps" ],
      [ "Minimap", "classproofps__dd_1_1_minimap.html", "classproofps__dd_1_1_minimap" ],
      [ "MsgBulletUpdateFromServer", "structproofps__dd_1_1_msg_bullet_update_from_server.html", "structproofps__dd_1_1_msg_bullet_update_from_server" ],
      [ "MsgCurrentWpnUpdateFromServer", "structproofps__dd_1_1_msg_current_wpn_update_from_server.html", "structproofps__dd_1_1_msg_current_wpn_update_from_server" ],
      [ "MsgDeathNotificationFromServer", "structproofps__dd_1_1_msg_death_notification_from_server.html", "structproofps__dd_1_1_msg_death_notification_from_server" ],
      [ "MsgGameSessionStateFromServer", "structproofps__dd_1_1_msg_game_session_state_from_server.html", "structproofps__dd_1_1_msg_game_session_state_from_server" ],
      [ "MsgMapChangeFromServer", "structproofps__dd_1_1_msg_map_change_from_server.html", "structproofps__dd_1_1_msg_map_change_from_server" ],
      [ "MsgMapItemUpdateFromServer", "structproofps__dd_1_1_msg_map_item_update_from_server.html", "structproofps__dd_1_1_msg_map_item_update_from_server" ],
      [ "MsgPlayerEventFromServer", "structproofps__dd_1_1_msg_player_event_from_server.html", "structproofps__dd_1_1_msg_player_event_from_server" ],
      [ "MsgServerInfoFromServer", "structproofps__dd_1_1_msg_server_info_from_server.html", "structproofps__dd_1_1_msg_server_info_from_server" ],
      [ "MsgUserCmdFromClient", "structproofps__dd_1_1_msg_user_cmd_from_client.html", "structproofps__dd_1_1_msg_user_cmd_from_client" ],
      [ "MsgUserNameChangeAndBootupDone", "structproofps__dd_1_1_msg_user_name_change_and_bootup_done.html", "structproofps__dd_1_1_msg_user_name_change_and_bootup_done" ],
      [ "MsgUserSetupFromServer", "structproofps__dd_1_1_msg_user_setup_from_server.html", "structproofps__dd_1_1_msg_user_setup_from_server" ],
      [ "MsgUserUpdateFromServer", "structproofps__dd_1_1_msg_user_update_from_server.html", "structproofps__dd_1_1_msg_user_update_from_server" ],
      [ "MsgWpnUpdateFromServer", "structproofps__dd_1_1_msg_wpn_update_from_server.html", "structproofps__dd_1_1_msg_wpn_update_from_server" ],
      [ "Networking", "classproofps__dd_1_1_networking.html", "classproofps__dd_1_1_networking" ],
      [ "Physics", "classproofps__dd_1_1_physics.html", "classproofps__dd_1_1_physics" ],
      [ "Player", "classproofps__dd_1_1_player.html", "classproofps__dd_1_1_player" ],
      [ "PlayerHandling", "classproofps__dd_1_1_player_handling.html", "classproofps__dd_1_1_player_handling" ],
      [ "PRooFPSappMsgId2ZStringPair", "structproofps__dd_1_1_p_roo_f_p_sapp_msg_id2_z_string_pair.html", "structproofps__dd_1_1_p_roo_f_p_sapp_msg_id2_z_string_pair" ],
      [ "PRooFPSddPGE", "classproofps__dd_1_1_p_roo_f_p_sdd_p_g_e.html", "classproofps__dd_1_1_p_roo_f_p_sdd_p_g_e" ],
      [ "Sounds", "classproofps__dd_1_1_sounds.html", "classproofps__dd_1_1_sounds" ],
      [ "WeaponHandling", "classproofps__dd_1_1_weapon_handling.html", "classproofps__dd_1_1_weapon_handling" ],
      [ "XHair", "classproofps__dd_1_1_x_hair.html", "classproofps__dd_1_1_x_hair" ]
    ] ],
    [ "EventListerTest", "class_event_lister_test.html", "class_event_lister_test" ],
    [ "GameModeTest", "class_game_mode_test.html", "class_game_mode_test" ],
    [ "MapcycleTest", "class_mapcycle_test.html", "class_mapcycle_test" ],
    [ "MapItemTest", "class_map_item_test.html", "class_map_item_test" ],
    [ "MapsTest", "class_maps_test.html", "class_maps_test" ],
    [ "MapTestsCommon", "class_map_tests_common.html", "class_map_tests_common" ],
    [ "PlayerTest", "class_player_test.html", "class_player_test" ],
    [ "RegTestBasicServerClient2Players", "class_reg_test_basic_server_client2_players.html", "class_reg_test_basic_server_client2_players" ],
    [ "RegTestMapChangeServerClient3Players", "class_reg_test_map_change_server_client3_players.html", "class_reg_test_map_change_server_client3_players" ],
    [ "TestableMapcycle", "class_testable_mapcycle.html", "class_testable_mapcycle" ],
    [ "TestableMaps", "class_testable_maps.html", "class_testable_maps" ]
];